# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.8.0 on Tue Oct 22 16:52:39 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Pointliste(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Pointliste.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((747, 475))
        self.SetTitle("Pointliste")

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)

        self.list_ctrl_Pointliste = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_ctrl_Pointliste.AppendColumn("Point_ID", format=wx.LIST_FORMAT_LEFT, width=66)
        self.list_ctrl_Pointliste.AppendColumn("Pfad", format=wx.LIST_FORMAT_LEFT, width=159)
        self.list_ctrl_Pointliste.AppendColumn("Tagname", format=wx.LIST_FORMAT_LEFT, width=177)
        self.list_ctrl_Pointliste.AppendColumn("Beschreibung", format=wx.LIST_FORMAT_LEFT, width=215)
        self.list_ctrl_Pointliste.AppendColumn("Schnittstelle", format=wx.LIST_FORMAT_LEFT, width=115)
        sizer_2.Add(self.list_ctrl_Pointliste, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_2)

        self.Layout()

        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.Point_uebernehmen, self.list_ctrl_Pointliste)
        # end wxGlade

    def Point_uebernehmen(self, event):  # wxGlade: Pointliste.<event_handler>
        global Tab, sperren
        if Tab == "Archiveditor":
            wx.GetApp().Hauptrahmen.Point_ID.SetValue(self.list_ctrl_Pointliste.GetItem(self.list_ctrl_Pointliste.GetFirstSelected()).Text)
        if Tab == "Export":
            wx.GetApp().Hauptrahmen.Point_ID_Export.SetValue(self.list_ctrl_Pointliste.GetItem(self.list_ctrl_Pointliste.GetFirstSelected()).Text)
        self.Close()
    def Liste_hinterlegen(self, Registerkarte):
        global Tab
        Tab = Registerkarte
# end of class Pointliste
