# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.8.0 on Tue Oct 22 16:52:39 2019
#

import wx, DH_Funktionen
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Points_Feldliste(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Points_Feldliste.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((200, 300))
        self.SetTitle("dialog")

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        self.list_ctrl_Feld_Liste = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_ctrl_Feld_Liste.AppendColumn("Feld", format=wx.LIST_FORMAT_LEFT, width=200)
        sizer_4.Add(self.list_ctrl_Feld_Liste, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_4)

        self.Layout()

        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.evt_uebernehmen, self.list_ctrl_Feld_Liste)
        # end wxGlade

    def evt_uebernehmen(self, event):  # wxGlade: Points_Feldliste.<event_handler>
        Liste = wx.GetApp().Hauptrahmen.Tagtabelle
        i = 0
        while i <= Liste.GetNumberCols():
            if Liste.GetColLabelValue(i) == "Point_ID":
                sperren = i
            i = i + 1
        Anz_Spalten = Liste.GetNumberCols()
        Spalte = -1
        if Liste.GetSelectedCols() == Anz_Spalten - 1 and len(Liste.GetSelectedCols()) > 0:
            Liste.AppendCols(1, True)
        else:
            if len(Liste.GetSelectedCols()) > 0:
                sel_Spalten = Liste.GetSelectedCols()
                sel_Spalten.sort(reverse=True)
                Spalte = sel_Spalten[0] + 1
            else:
                if Liste.GetGridCursorCol() > -1:
                    Spalte = Liste.GetGridCursorCol() + 1
                else:
                    Spalte = 0
        Liste.InsertCols(Spalte, 1, True)
        Parameter = self.list_ctrl_Feld_Liste.GetItem(self.list_ctrl_Feld_Liste.GetFirstSelected()).Text
        Liste.SetColLabelValue(Spalte, Parameter)
        sperren_alt = sperren
        i = 0
        while i <= Liste.GetNumberCols():
            if Liste.GetColLabelValue(i) == "Point_ID":
                sperren = i
            i = i + 1
        Zeile = 0
        while Zeile < Liste.GetNumberRows():
            DH_Funktionen.db.query("SELECT `" + Parameter + "` FROM `Tags` WHERE `Point_ID` = " + str(Liste.GetCellValue(Zeile,  sperren)) + ";")
            Ergebnis=DH_Funktionen.db.store_result()
            Satz = Ergebnis.fetch_row(maxrows=0, how=1)
            Liste.SetCellValue(Zeile,  Spalte,  Satz[0][Parameter])
            Zeile = Zeile + 1
        if sperren_alt > Spalte:
            Zeile = 0
            while Zeile <= Liste.GetNumberRows():
                Liste.SetReadOnly(Zeile, sperren, True)
                Liste.SetReadOnly(Zeile, sperren_alt, False)
                Zeile = Zeile + 1
        self.Close()
# end of class Tags_Feldliste
