#!/bin/sh
### BEGIN INIT INFO
# Provides:          dh
# Required-Start:    $remote_fs $syslog mysqld
# Required-Stop:     $remote_fs $syslog mysqld
# Default-Start:     2
# Default-Stop:      2 6
# Short-Description: DH starten / stoppen
# Description:       Startet / stopt die Schnittstellen fuer den DH.
### END INIT INFO
# Author: Ralf Meier
DESC="Startet / stopt die Schnittstellen fuer den DH"
#DAEMON=/opt/DH/DH_start.py

case "$1" in
  start)
        /opt/DH/DH_start.py
        ;;
  stop)
        /opt/DH/DH_stop.py
        ;;
esac
