CREATE DATABASE unidb;
FLUSH PRIVILEGES;
CREATE DATABASE DH;
FLUSH PRIVILEGES;
CREATE USER 'mariadb_admin'@'localhost' identified by 'unidb';
GRANT ALL privileges on *.* to 'mariadb_admin'@'localhost' with grant option;
CREATE USER 'DH_readonly'@'%';
GRANT SELECT ON `DH%`.* TO 'DH_readonly'@'%';
CREATE USER 'unidb'@'%' identified by 'nurunidb';
GRANT SELECT, INSERT, UPDATE, DELETE ON `unidb`.* TO 'unidb'@'%';
CREATE USER 'DH_write'@'%' identified by 'nurDH';
GRANT SELECT, INSERT, UPDATE, DELETE ON `DH`.* TO 'DH_write'@'%';
CREATE USER 'useradmin'@'localhost' identified by 'uadminpw';
GRANT SELECT, RELOAD, LOCK TABLES, CREATE USER ON *.* TO `useradmin`@`localhost` IDENTIFIED BY 'uadminpw' WITH GRANT OPTION;
CREATE USER 'admin'@'localhost' identified by 'b511e6d04233d58608dd559b2ff8f21d';
GRANT SELECT, INSERT, UPDATE, DELETE ON `DH`.* TO 'admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `unidb`.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;
